
db_server:
  restart: always
  image: microsoft/mssql-server-linux
  container_name: iisapp-db_server
  volumes:
    - /data/iisapp/db:/var/lib/mssql/data
  net: iisapp


web_server:
  restart: always
  image: microsoft/iis
  container_name: iisapp-web_server
  ports:
    - "443:443"
  volumes:
    - /data/iisapp/web/log:/var/log/iis
  net: iisapp

