
db_server:
  restart: always
  image: postgres
  container_name: db_server
  volumes:
    - /data/yougo/db:/var/lib/postgresql/data
  net: yougo

web_server:
  restart: always
  image: ubuntu
  container_name: web_server
  ports:
    - "443:443"
  volumes:
    - /data/yougo/web/log:/var/log/nginx
  net: yougo

